# Generated by Django 4.2.7 on 2023-11-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_usersprofile_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersprofile",
            name="archived",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
